pipeline{
    agent any

    stages{
        stage('Hello'){
            steps{
                echo 'Hello depuis un pipeline declaratif'
            }
        }
        stage('Info envirennement'){
            steps{
                echo "Nom de noeud Jenkis : ${env.NODE_NAME}"
                echo "Workspace: ${env.WORKSPACE}"
            }
        }
    }
}